---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- {name: bosh-config}
- {name: certificate}

run:
  path: bosh-config/update-cloud-config.sh
